name: Rust

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-lint:
    name: Build, test, lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update Rust
      run: rustup update

    - name: Build
      run: cargo build

    - name: Test
      run: cargo test

    - name: Docs
      run: cargo doc

    - name: Clippy
      run: cargo clippy -- -D warnings
