name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update Rust
      run: rustup update stable

    - name: Build
      run: cargo build --verbose --all-features

    - name: Test
      run: cargo test --verbose --all-features

    - name: Docs
      run: cargo doc --verbose --all-features


  build-macos:
    name: Build on macOS
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update Rust
      run: rustup update stable

    - name: Build
      run: cargo build --verbose --all-features

    - name: Test
      run: cargo test --verbose --all-features

    - name: Docs
      run: cargo doc --verbose --all-features


  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Rust
        run: rustup update stable

      - name: Build
        run: cargo build --verbose --all-features

      - name: Test
        run: cargo test --verbose --all-features

      - name: Docs
        run: cargo doc --verbose --all-features
